name: Deploy

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+

jobs:
  docker-setup:
    env:
      OWNER: ${{ secrets.OWNER }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Login
        run: |
          echo ${{ secrets.PASSWORD }} | docker login ghcr.io -u $OWNER  --password-stdin 

      - name: Build
        run: |
          docker build -t ghcr.io/$OWNER/webhooker:latest .
      - name: Docker push
        run: |
          docker push ghcr.io/$OWNER/webhooker:latest

  production:
    runs-on: ubuntu-latest
    needs: docker-setup
    environment:
      name: production
      url: https://webhooker.online/doc
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
      - name: copy builds to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_IP }} "docker service update --force --image ghcr.io/${{ secrets.OWNER }}/webhooker:latest webhooker_wh"
          
